// Squad Up — Category configuration map
// Used on both frontend (rendering fields, icons, colors) and as reference for backend validation.

export const SQUAD_CATEGORIES = {
  carpool: {
    key: 'carpool',
    label: 'Ride & Carpool',
    icon: '🚗',
    color: '#5B9BD5',
    fields: ['fromLocation', 'toLocation', 'departureTime', 'seats', 'vehicleType', 'costSplitMethod', 'detourTolerance', 'genderPreference', 'isRecurring'],
    quickTitle: (m) => `Going from ${m.fromLocation || '?'} to ${m.toLocation || '?'}`,
  },
  order_split: {
    key: 'order_split',
    label: 'Order & Delivery Split',
    icon: '🛒',
    color: '#E8C547',
    fields: ['platform', 'currentCartValue', 'targetThreshold', 'orderDeadline', 'deliveryAddress', 'upiHandle'],
    quickTitle: (m) => `Ordering on ${m.platform || 'app'} — need ₹${Math.max(0, (m.targetThreshold || 0) - (m.currentCartValue || 0))} more`,
  },
  food_order: {
    key: 'food_order',
    label: 'Group Food Order',
    icon: '🍔',
    color: '#D4845A',
    fields: ['restaurant', 'platform', 'menuItems', 'perPersonBudget', 'orderDeadline', 'paymentMethod', 'deliveryAddress'],
    quickTitle: (m) => `Group order from ${m.restaurant || 'restaurant'}`,
  },
  ticket_split: {
    key: 'ticket_split',
    label: 'Event & Ticket Split',
    icon: '🎟️',
    color: '#9B7ED4',
    fields: ['eventName', 'eventDate', 'venue', 'ticketPrice', 'groupSizeForDiscount', 'bookingDeadline', 'totalSavings', 'bookerName'],
    quickTitle: (m) => `${m.eventName || 'Event'} tickets — group discount`,
  },
  bulk_buy: {
    key: 'bulk_buy',
    label: 'Bulk Buy & Wholesale',
    icon: '🛍️',
    color: '#7BC67E',
    fields: ['itemName', 'quantity', 'source', 'totalCost', 'perUnitCost', 'minBulkQuantity', 'pickupPoint'],
    quickTitle: (m) => `Bulk buy: ${m.itemName || 'items'}`,
  },
  tool_rent: {
    key: 'tool_rent',
    label: 'Tool & Equipment Rent',
    icon: '🧰',
    color: '#D46A6A',
    fields: ['itemToRent', 'rentalProvider', 'rentalDuration', 'totalCost', 'splitCount', 'pickupDelivery', 'damageDeposit'],
    quickTitle: (m) => `Rent split: ${m.itemToRent || 'equipment'}`,
  },
  travel: {
    key: 'travel',
    label: 'Travel & Trip Planning',
    icon: '🧳',
    color: '#5B9BD5',
    fields: ['destination', 'travelDates', 'tripType', 'budgetPerPerson', 'accommodationType', 'spotsAvailable', 'itinerary', 'genderPreference'],
    quickTitle: (m) => `Trip to ${m.destination || 'destination'}`,
  },
  courier: {
    key: 'courier',
    label: 'Courier & Shipping',
    icon: '📦',
    color: '#A09880',
    fields: ['pickupLocation', 'destinationCity', 'packageWeight', 'courierService', 'currentCost', 'splitCost', 'pickupDate'],
    quickTitle: (m) => `Courier to ${m.destinationCity || 'city'} — split cost`,
  },
  subscription: {
    key: 'subscription',
    label: 'Subscription Split',
    icon: '💻',
    color: '#E8C547',
    fields: ['serviceName', 'planType', 'totalMonthlyCost', 'maxSlots', 'slotsRemaining', 'renewalDate', 'ownerUpiHandle', 'notes'],
    quickTitle: (m) => `${m.serviceName || 'Service'} ${m.planType || 'plan'} — ₹${m.totalMonthlyCost ? Math.ceil(m.totalMonthlyCost / (m.maxSlots || 1)) : '?'}/person`,
  },
  fitness: {
    key: 'fitness',
    label: 'Fitness & Classes',
    icon: '🏋️',
    color: '#7BC67E',
    fields: ['activityType', 'venue', 'dateTime', 'duration', 'totalCost', 'perPersonCost', 'isRecurring', 'skillLevel', 'maxParticipants'],
    quickTitle: (m) => `${m.activityType || 'Activity'} at ${m.venue || 'venue'}`,
  },
  community_buy: {
    key: 'community_buy',
    label: 'Community Group Buy',
    icon: '🌱',
    color: '#7BC67E',
    fields: ['serviceProduct', 'provider', 'minGroupSize', 'priceAlone', 'groupPrice', 'savingsPerPerson', 'organizerContact', 'deadline'],
    quickTitle: (m) => `Group buy: ${m.serviceProduct || 'item'}`,
  },
  study_group: {
    key: 'study_group',
    label: 'Study & Skill Groups',
    icon: '🎓',
    color: '#9B7ED4',
    fields: ['subject', 'level', 'format', 'schedule', 'courseName', 'courseCost', 'groupSizeTarget'],
    quickTitle: (m) => `${m.subject || 'Study'} group — ${m.level || 'all levels'}`,
  },
  custom: {
    key: 'custom',
    label: 'Something Else',
    icon: '✨',
    color: '#E8C547',
    fields: ['customCategoryLabel', 'customBenefitType', 'customBenefitNote', 'userDefinedTags'],
    quickTitle: (m) => m.customCategoryLabel || 'Custom squad',
  },
};

export const CATEGORY_KEYS = Object.keys(SQUAD_CATEGORIES);

export const BENEFIT_TYPES = [
  { value: 'save_money', label: 'Save Money', icon: '💰' },
  { value: 'save_time', label: 'Save Time', icon: '⏱️' },
  { value: 'safety', label: 'Safety', icon: '🛡️' },
  { value: 'more_fun', label: 'More Fun', icon: '🎉' },
  { value: 'min_group', label: 'Need Minimum Group', icon: '👥' },
  { value: 'other', label: 'Other', icon: '✍️' },
];

// Field labels & types for dynamic rendering
export const FIELD_DEFINITIONS = {
  fromLocation: { label: 'From', type: 'text', placeholder: 'Pickup location' },
  toLocation: { label: 'To', type: 'text', placeholder: 'Drop location' },
  departureTime: { label: 'Departure Time', type: 'datetime-local' },
  seats: { label: 'Seats Available', type: 'number', min: 1, max: 8 },
  vehicleType: { label: 'Vehicle', type: 'select', options: ['bike', 'auto', 'car', 'suv'] },
  detourTolerance: { label: 'Detour Tolerance (km)', type: 'number', min: 0, max: 20 },
  genderPreference: { label: 'Gender Preference', type: 'select', options: ['any', 'male', 'female'] },
  platform: { label: 'Platform', type: 'text', placeholder: 'Blinkit, Swiggy, Amazon...' },
  currentCartValue: { label: 'Current Cart Value (₹)', type: 'number' },
  targetThreshold: { label: 'Free Delivery Threshold (₹)', type: 'number' },
  orderDeadline: { label: 'Ordering In', type: 'datetime-local' },
  deliveryAddress: { label: 'Delivery Area', type: 'text', placeholder: 'Your area for proximity' },
  upiHandle: { label: 'UPI Handle', type: 'text', placeholder: 'your@upi' },
  restaurant: { label: 'Restaurant', type: 'text' },
  menuItems: { label: 'Menu / Items', type: 'textarea', placeholder: 'List items or link to menu' },
  perPersonBudget: { label: 'Budget Per Person (₹)', type: 'number' },
  paymentMethod: { label: 'Payment Collection', type: 'select', options: ['UPI', 'Cash', 'Split app'] },
  eventName: { label: 'Event Name', type: 'text' },
  eventDate: { label: 'Event Date', type: 'date' },
  venue: { label: 'Venue', type: 'text' },
  ticketPrice: { label: 'Ticket Price (₹)', type: 'number' },
  groupSizeForDiscount: { label: 'Group Size for Discount', type: 'number' },
  bookingDeadline: { label: 'Booking Deadline', type: 'datetime-local' },
  totalSavings: { label: 'Savings If Group Forms (₹)', type: 'number' },
  bookerName: { label: 'Who Books', type: 'text' },
  itemName: { label: 'Item Name', type: 'text' },
  quantity: { label: 'Total Quantity', type: 'text' },
  source: { label: 'Store / Supplier', type: 'text' },
  perUnitCost: { label: 'Per Unit Cost (₹)', type: 'number' },
  minBulkQuantity: { label: 'Min Bulk Quantity', type: 'number' },
  pickupPoint: { label: 'Pickup Point', type: 'text' },
  itemToRent: { label: 'Item to Rent', type: 'text' },
  rentalProvider: { label: 'Rental Provider', type: 'text' },
  rentalDuration: { label: 'Duration', type: 'text', placeholder: 'e.g. 2 days' },
  splitCount: { label: 'Split Among (people)', type: 'number' },
  pickupDelivery: { label: 'Pickup / Delivery', type: 'select', options: ['pickup', 'delivery', 'both'] },
  damageDeposit: { label: 'Damage Deposit (₹)', type: 'number' },
  destination: { label: 'Destination', type: 'text' },
  travelDates: { label: 'Travel Dates', type: 'text', placeholder: 'Mar 15–18' },
  tripType: { label: 'Trip Type', type: 'select', options: ['leisure', 'adventure', 'work', 'religious'] },
  budgetPerPerson: { label: 'Budget Per Person (₹)', type: 'number' },
  accommodationType: { label: 'Stay', type: 'select', options: ['airbnb', 'hotel', 'hostel', 'camping'] },
  spotsAvailable: { label: 'Spots Available', type: 'number' },
  itinerary: { label: 'Itinerary (optional)', type: 'textarea' },
  pickupLocation: { label: 'Pickup Location', type: 'text' },
  destinationCity: { label: 'Destination City', type: 'text' },
  packageWeight: { label: 'Package Weight (kg approx)', type: 'text' },
  courierService: { label: 'Preferred Courier', type: 'text' },
  currentCost: { label: 'Full Courier Cost (₹)', type: 'number' },
  splitCost: { label: 'Your Split Cost (₹)', type: 'number' },
  pickupDate: { label: 'Pickup Date', type: 'date' },
  serviceName: { label: 'Service Name', type: 'text', placeholder: 'Netflix, Spotify...' },
  planType: { label: 'Plan Type', type: 'text', placeholder: 'Family, Premium...' },
  totalMonthlyCost: { label: 'Total Monthly Cost (₹)', type: 'number' },
  maxSlots: { label: 'Total Slots', type: 'number' },
  slotsRemaining: { label: 'Slots Remaining', type: 'number' },
  renewalDate: { label: 'Next Renewal', type: 'date' },
  ownerUpiHandle: { label: 'Owner UPI', type: 'text' },
  notes: { label: 'Notes', type: 'textarea' },
  activityType: { label: 'Activity', type: 'text', placeholder: 'Badminton, Yoga...' },
  duration: { label: 'Duration (mins)', type: 'number' },
  perPersonCost: { label: 'Cost Per Person (₹)', type: 'number' },
  skillLevel: { label: 'Skill Level', type: 'select', options: ['beginner', 'intermediate', 'advanced', 'any'] },
  serviceProduct: { label: 'Service / Product', type: 'text' },
  provider: { label: 'Provider', type: 'text' },
  minGroupSize: { label: 'Min Group Size', type: 'number' },
  priceAlone: { label: 'Price Alone (₹)', type: 'number' },
  groupPrice: { label: 'Group Price (₹)', type: 'number' },
  savingsPerPerson: { label: 'Savings Per Person (₹)', type: 'number' },
  organizerContact: { label: 'Organizer Contact', type: 'text' },
  deadline: { label: 'Deadline', type: 'datetime-local' },
  subject: { label: 'Subject / Skill', type: 'text' },
  level: { label: 'Level', type: 'select', options: ['beginner', 'intermediate', 'advanced'] },
  format: { label: 'Format', type: 'select', options: ['online', 'in-person', 'hybrid'] },
  schedule: { label: 'Schedule', type: 'text', placeholder: 'Weekdays 6pm, Sundays 10am...' },
  courseName: { label: 'Course Name', type: 'text' },
  courseCost: { label: 'Course Cost (₹)', type: 'number' },
  groupSizeTarget: { label: 'Target Group Size', type: 'number' },
  customCategoryLabel: { label: 'What do you call this?', type: 'text', placeholder: 'e.g. Terrace Gardening Group' },
  customBenefitType: { label: 'Benefit of doing this together', type: 'benefit_select' },
  customBenefitNote: { label: 'Tell us in your own words', type: 'textarea', placeholder: 'Why is this better together?' },
  userDefinedTags: { label: 'Tags (max 5)', type: 'tag_input' },
  dateTime: { label: 'Date & Time', type: 'datetime-local' },
  totalCost: { label: 'Total Cost (₹)', type: 'number' },
  maxParticipants: { label: 'Max Participants', type: 'number' },
};

// Inspire Me — example custom posts
export const CUSTOM_EXAMPLES = [
  { title: 'Terrace Gardening Group', description: 'Share seeds, soil & tools for terrace gardening', benefitType: 'save_money', people: 4, tags: ['gardening', 'terrace', 'plants'] },
  { title: 'Diwali Decoration Squad', description: 'Bulk decoration order split across flats', benefitType: 'save_money', people: 6, tags: ['diwali', 'decoration', 'festival'] },
  { title: 'Dog Walking Buddy', description: 'Morning walk partner for our lane', benefitType: 'safety', people: 2, tags: ['dog', 'walking', 'morning'] },
  { title: 'Newspaper Bulk Subscription', description: 'Negotiate group rate for 10 flats', benefitType: 'save_money', people: 10, tags: ['newspaper', 'subscription', 'building'] },
  { title: 'RO Water Can Group Order', description: 'Weekly delivery cost split', benefitType: 'save_money', people: 5, tags: ['water', 'delivery', 'weekly'] },
  { title: 'Building Badminton Tournament', description: 'Need minimum 16 players for a tournament', benefitType: 'min_group', people: 16, tags: ['badminton', 'sports', 'tournament'] },
  { title: 'Homemade Tiffin Group', description: 'One person cooks per day, rotation among 5', benefitType: 'save_time', people: 5, tags: ['tiffin', 'cooking', 'rotation'] },
  { title: 'EV Charging Slot Sharing', description: 'Coordinate building charging schedule', benefitType: 'save_time', people: 8, tags: ['ev', 'charging', 'schedule'] },
];
